alias: Check Queued Notifications
sequence:
  - if:
      - condition: numeric_state
        entity_id: todo.queued_notifications
        above: 0
    then:
      - service: todo.get_items
        target:
          entity_id: todo.queued_notifications
        data:
          status: needs_action
        response_variable: result
      - variables:
          remaining: |-
            {%- set ns = namespace(count=1) %}
            {%- for i in result["todo.queued_notifications"]["items"] %}
              {%- if now() <= as_datetime(i.due) %}
                {{ ns.count }}. {{ i.summary }}.
                {%- set ns.count = ns.count + 1 %}
              {%- endif %}
            {%- endfor %}
      - if:
          - condition: template
            value_template: "{{ remaining != '' }}"
        then:
          - service: script.notify
            data:
              message: You have queued notifications. {{ remaining }}
              no_greeting: true
              speak_targets: []
              speak_on_voice_boxes_with_presence: true
              speak_on_last_voice_box_triggered: false
              do_not_queue: true
          - service: todo.remove_item
            data:
              item: >-
                {{ result["todo.queued_notifications"]["items"] | map(attribute='summary') | list }}
            target:
              entity_id: todo.queued_notifications
mode: single
icon: mdi:speaker-message
