alias: Time triggers weather warning notify
description: ""
trigger:
  - platform: state
    entity_id:
      - weather.home
condition:
  - condition: template
    value_template: "{{ has_value('weather.home') }}"
  - condition: template
    value_template: >-
      {{ (now() - state_attr('automation.time_triggers_weather_warning_notify', 'last_triggered')) > timedelta(hours=6) }}
action:
  - service: weather.get_forecasts
    data:
      type: hourly
    target:
      entity_id: weather.home
    response_variable: weather
  - variables:
      result: >-
        {%- set fc_24 = weather['weather.home']['forecast'][1:25] %}
        {%- set ns = namespace(warning=[]) %}
        {%- if fc_24 | selectattr('condition', 'search', 'snow') | first is defined %}
          {%- set ns.warning = ns.warning + ['snow'] %}
        {%- endif %}
        {%- if fc_24 | selectattr('condition', 'search', 'lightning') | first is defined %}
          {%- set ns.warning = ns.warning + ['lightning'] %}
        {%- endif %}
        {%- if fc_24 | selectattr('condition', 'search', 'hail') | first is defined %}
          {%- set ns.warning = ns.warning + ['hail'] %}
        {%- endif %}
        {%- if ns.warning %}
          Be careful, forecast for the next 24 hours is now announcing some {{ ns.warning | join(' and ') }}.
        {%- else %}
          {{ false }}
        {%- endif %}
  - if:
      - condition: template
        value_template: "{{ result != false }}"
    then:
      - service: script.notify
        data:
          message: "{{ result }}"
          speak_on_last_voice_box_triggered: false
          speak_on_voice_boxes_with_presence: true
          speak_targets: []
          title: Weather Warning
          send_to_phone: true
mode: single
